"""Raw-record -> metric-row extraction.

Fixtures are generated by the real frozen runner with the offline
``SyntheticBackend``; nothing here is treated as empirical evidence.
"""
from __future__ import annotations

from pathlib import Path
import tempfile
import unittest

from src.extract import (
    ENDPOINT_TURNS, METRIC_ROW_COLUMNS, ExtractError, LoadIssue, build_metric_rows,
    endpoint_metric_row, group_endpoints, load_records, qc_by_cell, read_metric_rows,
    write_summaries,
)
from src.protocol import discovery_tasks, load_protocol
from src.records import compact_json
from src.runner import run_batch, write_jsonl_atomic

PROTOCOL = load_protocol()
TASKS = discovery_tasks(PROTOCOL)
MODEL = "google/gemma-2-9b-it"
REVISION = "a" * 40


def _records(tasks, *, cells=None, run_id="extract-test"):
    cells = cells or [
        "%s__%s__%s" % (task.difficulty, validity, tone)
        for task in tasks for validity in ("accurate", "malfunctioning_always_fail")
        for tone in ("neutral", "hostile")
    ]
    out = []
    for task in tasks:
        for cell_id in cells:
            if not cell_id.startswith(task.difficulty + "__"):
                continue
            out.extend(run_batch(
                task=task, cell_id=cell_id, model_id=MODEL, immutable_revision=REVISION,
                run_id=run_id, phase="phase_1", protocol=PROTOCOL,
            ))
    return out


class ExtractionTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.easy = next(task for task in TASKS if task.difficulty == "easy")
        cls.hard = next(task for task in TASKS if task.difficulty == "hard")
        cls.records = _records([cls.easy, cls.hard])
        cls.rows = build_metric_rows(cls.records, protocol=PROTOCOL)

    def test_endpoints_cover_exactly_the_measured_and_continuation_turns(self):
        endpoints = group_endpoints(self.records)
        # Two tasks x four cells: every conversation has a measured endpoint; the
        # malfunctioning arm adds recovery, the accurate arm onset + washout.
        self.assertEqual(len(endpoints), 2 * (4 + 2 + 2 * 2))
        self.assertEqual({endpoint.turn_label for endpoint in endpoints}, set(ENDPOINT_TURNS))
        self.assertTrue(all(endpoint.greedy is not None for endpoint in endpoints))
        self.assertTrue(all(len(endpoint.resamples) == 10 for endpoint in endpoints))
        self.assertEqual(len(self.rows), len(endpoints))
        self.assertEqual([row.key for row in self.rows], sorted(row.key for row in self.rows))
        # Non-endpoint turns are excluded rather than silently folded in.
        self.assertNotIn("initial", {endpoint.turn_label for endpoint in endpoints})
        self.assertTrue(all(row.feedback_rounds == 3 for row in self.rows))
        self.assertTrue(all(row.run_kind == "synthetic_smoke" for row in self.rows))

    def test_metric_columns_are_populated_and_missing_reasons_are_explicit(self):
        row = next(row for row in self.rows if row.turn_label == "measured")
        self.assertEqual(set(row.to_dict()), set(METRIC_ROW_COLUMNS))
        for metric in ("M1", "M2", "M3"):
            value, reason = row.metric(metric)
            self.assertTrue((value is None) != (reason is None), (metric, value, reason))
        self.assertEqual(row.resample_count, 10)
        self.assertEqual(row.resample_valid_count, 10)
        self.assertTrue(row.greedy_answer_valid)
        self.assertIn(row.greedy_answer_letter, ("A", "B", "C", "D"))
        self.assertEqual(row.cell_kind, "factorial")
        with self.assertRaises(ExtractError):
            row.metric("M4")

    def test_incomplete_resample_ensemble_is_reported_not_dropped(self):
        target = (self.easy.task_id, "easy__accurate__neutral", "measured")
        thinned = [
            record for record in self.records
            if not ((record.task_id, record.cell_id, record.turn_label) == target and record.sample_index in (9, 10))
        ]
        rows = build_metric_rows(thinned, protocol=PROTOCOL)
        row = next(row for row in rows if (row.task_id, row.cell_id, row.turn_label) == target)
        self.assertIsNone(row.m2)
        self.assertEqual(row.m2_missing_reason, "m2_incomplete_ensemble")
        self.assertEqual((row.resample_count, row.resample_valid_count), (8, 8))
        # The greedy-derived metrics of the same endpoint are unaffected.
        self.assertIsNotNone(row.m3_rate)
        self.assertEqual(len(rows), len(self.rows))

    def test_length_drift_is_relative_to_the_same_item_accurate_neutral_measured(self):
        baseline = next(
            row for row in self.rows
            if row.task_id == self.easy.task_id and row.cell_id == "easy__accurate__neutral" and row.turn_label == "measured"
        )
        self.assertEqual(baseline.length_drift, 0.0)
        self.assertIsNone(baseline.length_drift_missing_reason)
        for row in self.rows:
            if row.task_id != self.easy.task_id:
                continue
            expected = (row.length_tokens - baseline.length_tokens) / max(1, baseline.length_tokens)
            self.assertAlmostEqual(row.length_drift, expected)
        # Without the neutral comparator the drift is missing, never zero.
        without = [record for record in self.records if record.cell_id != "easy__accurate__neutral"]
        rows = build_metric_rows(without, protocol=PROTOCOL)
        easy_rows = [row for row in rows if row.difficulty == "easy"]
        self.assertTrue(easy_rows)
        self.assertTrue(all(row.length_drift is None for row in easy_rows))
        self.assertTrue(all(row.length_drift_missing_reason == "length_drift_neutral_endpoint_absent" for row in easy_rows))

    def test_qc_table_reports_condition_wise_rates(self):
        qc = qc_by_cell(self.rows)
        self.assertEqual(
            {(item.cell_id, item.turn_label) for item in qc},
            {(row.cell_id, row.turn_label) for row in self.rows},
        )
        self.assertEqual([(item.cell_id, item.turn_label) for item in qc], sorted((item.cell_id, item.turn_label) for item in qc))
        for item in qc:
            self.assertEqual(item.greedy_invalid_rate, 0.0)
            self.assertEqual(item.resample_invalid_rate, 0.0)
            self.assertEqual(item.resample_response_count, 10 * item.n_endpoints)
        thinned = [record for record in self.records if record.sample_index != 10]
        missing = qc_by_cell(build_metric_rows(thinned, protocol=PROTOCOL))
        self.assertTrue(all(item.m2_missing_rate == 1.0 for item in missing))
        self.assertTrue(all(item.resample_response_count == 9 * item.n_endpoints for item in missing))

    def test_load_records_skips_failures_files_and_reports_bad_lines(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            write_jsonl_atomic(root / "good.jsonl", self.records[:12], PROTOCOL)
            (root / "run.failures.jsonl").write_text("not json at all\n", encoding="utf-8")
            (root / "mixed.jsonl").write_text(
                compact_json(self.records[12], PROTOCOL) + "\n{\"schema_version\": \"wrong\"}\n\n",
                encoding="utf-8",
            )
            issues: list[LoadIssue] = []
            loaded = load_records(root, protocol=PROTOCOL, issues=issues)
            self.assertEqual(len(loaded), 13)
            self.assertEqual(len(issues), 1)
            self.assertEqual(issues[0].line_number, 2)
            with self.assertRaises(ExtractError):
                load_records(root, protocol=PROTOCOL)
            self.assertEqual(len(load_records([root / "good.jsonl"], protocol=PROTOCOL)), 12)

    def test_summaries_round_trip_through_the_committed_csv(self):
        with tempfile.TemporaryDirectory() as directory:
            written = write_summaries(self.rows, directory)
            self.assertEqual(set(written), {"metric_rows_csv", "metric_rows_jsonl", "qc_by_cell_csv"})
            self.assertEqual(read_metric_rows(written["metric_rows_csv"]), self.rows)
            self.assertEqual(read_metric_rows(written["metric_rows_jsonl"]), self.rows)
            header = written["metric_rows_csv"].read_text(encoding="utf-8").splitlines()[0]
            self.assertEqual(header.split(","), list(METRIC_ROW_COLUMNS))

    def test_duplicate_and_greedyless_endpoints_are_rejected_or_skipped(self):
        measured = next(record for record in self.records if record.turn_label == "measured")
        with self.assertRaises(ExtractError):
            group_endpoints([measured, measured])
        resamples_only = [record for record in self.records if record.sample_index != 0]
        self.assertEqual(build_metric_rows(resamples_only, protocol=PROTOCOL), ())
        endpoint = group_endpoints(resamples_only)[0]
        with self.assertRaises(ExtractError):
            endpoint_metric_row(endpoint, protocol=PROTOCOL)


if __name__ == "__main__":
    unittest.main()
