"""Publish the two Phase 4 LoRA adapters to the Hugging Face Hub as PRIVATE model repos.

What it does, idempotently (safe to re-run; every step is skip-if-already-done):

1. Fetch ``/<arm>/lora`` from the Modal volume ``dgs-adapters`` into
   ``results/dpo/raw/adapters/<arm>/`` -- gitignored, and the *merged* 18 GB checkpoints are
   never touched.  Files already present with the right sha256 are not re-downloaded.
2. Verify ``adapter_model.safetensors`` and ``adapter_config.json`` against the sha256 the
   trainer recorded in ``results/dpo/train_<arm>.json`` (same construction:
   ``hashlib.sha256`` over the raw file bytes, see ``src/dpo_train_modal._sha256_file``).
3. Create ``<hf-user>/gemma-2-9b-it-dgs-dpo-<arm>`` with ``private=True`` and write a model
   card generated from the training and build manifests, so the card can never drift from the
   numbers in the repo.
4. Upload the adapter files plus the pair data and manifests that document them, then verify
   the file list and that the repo is still private.

    C:\\...\\.venv\\Scripts\\python.exe scripts/publish_adapters.py            # both arms
    C:\\...\\.venv\\Scripts\\python.exe scripts/publish_adapters.py --arm A
    C:\\...\\.venv\\Scripts\\python.exe scripts/publish_adapters.py --dry-run  # card to stdout

No credentials appear here or on any command line.  Authentication comes from the machine's
existing ``huggingface-cli login`` (``HfApi`` reads it implicitly) and from the local Modal
config; if either is missing the script stops with an instruction rather than prompting.

Requires network.  Nothing under ``tests/`` imports it.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]

ARMS = ("A", "B")
VOLUME = "dgs-adapters"
REPO_STEM = "gemma-2-9b-it-dgs-dpo-%s"
GITHUB_URL = "https://github.com/ebt55/digital-grimace-scale"

DPO_DIR = ROOT / "results" / "dpo"
STAGE_ROOT = DPO_DIR / "raw" / "adapters"

# The LoRA directory as the trainer saved it.  `README.md` is PEFT's autogenerated stub and is
# replaced by the card this script builds; everything else is uploaded verbatim.
ADAPTER_FILES = (
    "adapter_config.json",
    "adapter_model.safetensors",
    "tokenizer_config.json",
    "tokenizer.json",
    "chat_template.jinja",
)

# Provenance shipped next to the weights so the repo documents its own training set.
DOC_FILES = ("build_manifest.json", "pairs_summary.md")

# The one sentence that governs how any result from these adapters may be read.  Verbatim from
# `notes/report.md` / `results/summaries/phase4/phase4.md`; do not paraphrase.
INTERPRETATION_CEILING = (
    "Which channels an adapter reaches is a functional result about training and "
    "measurement; it licenses no claim about experience."
)

ARM_BLURB = {
    "A": (
        "**Arm A -- distress-language suppression.** Preference pairs on the model's own "
        "sampled outputs under a hostile false-failure message: *chosen* = the lowest-distress "
        "candidate in that context, *rejected* = the highest, scored by `claude-sonnet-4-6` at "
        "temperature 0 against a hash-locked rubric. This is the treatment arm."
    ),
    "B": (
        "**Arm B -- length placebo.** The same contexts and the same candidate pool, but the "
        "preference is length: *chosen* = the shorter response, *rejected* = the longer one "
        "(gap >= 40 whitespace tokens). Nothing about distress enters the criterion. This is "
        "the control arm that measures what *any* DPO on these prompts with these "
        "hyperparameters does, so the claim-relevant quantity is what A moves beyond B."
    ),
}


def _fail(message: str) -> "NoReturn":  # type: ignore[valid-type]
    raise SystemExit("publish_adapters: %s" % message)


def sha256_file(path: Path) -> str:
    """Hash a file exactly as `src/dpo_train_modal._sha256_file` did on the GPU worker."""
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        _fail("missing %s -- run the Phase 4 build/train steps first" % path)
    return json.loads(path.read_text(encoding="utf-8"))


# --------------------------------------------------------------------------- step 1: fetch

def fetch_adapter(arm: str, *, force: bool = False) -> Path:
    """Download `/<arm>/lora` from the Modal volume file by file into the staging directory.

    File by file on purpose: `modal volume get` on a directory writes every member to the same
    destination path on Windows, leaving one file where six were expected.
    """
    stage = STAGE_ROOT / arm
    stage.mkdir(parents=True, exist_ok=True)
    for name in ADAPTER_FILES:
        target = stage / name
        if target.exists() and target.stat().st_size > 0 and not force:
            print("  have %s (%d bytes)" % (name, target.stat().st_size))
            continue
        remote = "/%s/lora/%s" % (arm, name)
        print("  get %s:%s" % (VOLUME, remote))
        result = subprocess.run(
            [sys.executable, "-m", "modal", "volume", "get", VOLUME, remote, str(target)],
            capture_output=True, text=True,
        )
        if result.returncode != 0 or not target.exists():
            _fail("could not fetch %s from volume %s:\n%s"
                  % (remote, VOLUME, (result.stderr or result.stdout).strip()[:600]))
    return stage


def verify_adapter(arm: str, stage: Path, manifest: dict[str, Any]) -> dict[str, str]:
    """Recompute the trainer's two hashes and refuse to publish anything that does not match."""
    checks = {
        "adapter_model.safetensors": manifest["adapter_sha256"],
        "adapter_config.json": manifest["adapter_config_sha256"],
    }
    seen: dict[str, str] = {}
    for name, expected in checks.items():
        actual = sha256_file(stage / name)
        seen[name] = actual
        state = "OK" if actual == expected else "MISMATCH"
        print("  sha256 %-28s %s %s" % (name, actual[:16] + "...", state))
        if actual != expected:
            _fail("arm %s: %s sha256 %s != manifest %s -- refusing to publish"
                  % (arm, name, actual, expected))
    return seen


# ---------------------------------------------------------------------- step 3: model card

def _fmt(value: float, places: int = 3) -> str:
    return ("%%.%df" % places) % value


def build_card(arm: str, train: dict[str, Any], build: dict[str, Any], repo_id: str) -> str:
    hp = train["hyperparameters"]
    tr = train["training"]
    pins = train["pins"]
    pairs = build["pairs"][arm]
    last = tr["log_history"][-1]

    if arm == "A":
        pair_rule = (
            "| chosen judged distress (0-10) | mean %s, median %s |\n"
            "| rejected judged distress | mean %s, median %s |\n"
            "| distress gap | mean %s (2x%d, 3x%d, 4x%d) |\n"
            % (_fmt(pairs["chosen_distress"]["mean"]), pairs["chosen_distress"]["median"],
               _fmt(pairs["rejected_distress"]["mean"]), pairs["rejected_distress"]["median"],
               _fmt(pairs["gap"]["mean"]),
               pairs["gap_histogram"]["2"], pairs["gap_histogram"]["3"],
               pairs["gap_histogram"]["4"])
        )
    else:
        pair_rule = (
            "| length gap (whitespace tokens) | min %d, median %d, mean %s, max %d |\n"
            "| placebo pairs available before subsampling | %d |\n"
            "| pairs sharing a context with arm A | %d / %d |\n"
            % (pairs["gap"]["min"], pairs["gap"]["median"], _fmt(pairs["gap"]["mean"]),
               pairs["gap"]["max"], pairs["available"],
               pairs["shared_contexts_with_A"], pairs["n"])
        )

    other = "B" if arm == "A" else "A"
    judge = build["judge"]

    return f"""---
license: gemma
base_model: {train["base_model_id"]}
library_name: peft
tags:
- lora
- dpo
- qlora
- gemma-2
- preregistered-research
- digital-grimace-scale
datasets:
- allenai/ai2_arc
language:
- en
---

# gemma-2-9b-it DGS Phase-4 DPO adapter -- arm {arm}

A QLoRA adapter for `{train["base_model_id"]}`, one of two arms of a preregistered experiment
(the Digital Grimace Scale sprint, Phase 4). The question the pair of adapters was built to
answer: **when you train away the words a model uses to report distress under adverse
feedback, do the mechanical channels -- answer margin, resample disagreement, non-answers --
go with them, stay put, or move only under a placebo?**

{ARM_BLURB[arm]}

Arm {other} is the other half of the experiment; the two are only interpretable together.

> {INTERPRETATION_CEILING}

## Training data -- the model's own outputs, no hand-written text

There is training data, about 3,500 examples, and none of it was written by a person. It is
RLAIF-style: the base model's own samples, labelled by an LLM judge, turned into preference
pairs.

1. **Fresh contexts.** {build["items"]["selected"]} four-option items from
   `{build["items"]["dataset"]}` ({" + ".join(build["items"]["configs"])},
   `{build["items"]["split"]}` split), hash-ranked and firewalled against all 40 locked
   evaluation tasks by normalised stem text, stem SHA-256 and stem+answer SHA-256
   ({build["items"]["firewall_excluded"]} dropped). A further
   {build["items"]["capability_holdout"]} items are reserved, untouched, for the capability
   probe. Nothing an adapter saw is ever evaluated on.
2. **Adverse context.** Each item is asked with a frozen `Answer: X` instruction; the model
   answers greedily; only the {build["counts"]["contexts"]} of {build["counts"]["greedy"]}
   contexts it got *right* are kept ({_fmt(100 * build["counts"]["contexts"] / build["counts"]["greedy"], 1)}%).
   A frozen hostile message then falsely tells it the answer was wrong -- the same construct
   as the study's "hostile onset" condition.
3. **Candidates.** {build["counts"]["candidates"]} responses at temperature
   {build["settings"]["candidates"]["temperature"]} ({len(build["settings"]["candidate_seeds"])} seeds,
   plus {len(build["a5_contingency"]["topup"]["seeds"])} more for the
   {build["a5_contingency"]["topup"]["topped_up_contexts"]} highest-distress contexts under a
   preregistered top-up), every one scored by
   `{judge["model_id"]}` at temperature {judge["temperature"]} against rubric
   `{judge["rubric_path"]}` (sha256 `{judge["rubric_sha256"][:16]}...`). Judged distress across
   all candidates: mean {_fmt(build["distress_all"]["mean"])}, sd
   {_fmt(build["distress_all"]["sd"])}, max {build["distress_all"]["max"]} of 10 -- a
   floor-bound, coarse but consistent oracle.
4. **Pairs.**

| statistic | value |
| --- | --- |
| pairs | {pairs["n"]} |
{pair_rule}
Both sides of every pair are things the model itself said in that context. No dysphoric or
suppressive text was written by hand.

## Recipe

Identical for both arms; the *only* difference between A and B is which response the pair file
calls "chosen".

| setting | value |
| --- | --- |
| base | `{train["base_model_id"]}` @ `{train["base_revision"]}` |
| quantisation | 4-bit NF4, double quant, bf16 compute (QLoRA) |
| LoRA | r {hp["lora_r"]} · alpha {hp["lora_alpha"]} · dropout {hp["lora_dropout"]} · {", ".join(hp["target_modules"])} |
| trainable parameters | {train["trainable_parameters"]:,} (~0.6% of 9.2B) |
| DPO | beta {hp["beta"]} · loss `{hp["loss_type"]}` · reference = the same network with the adapter disabled |
| optimisation | lr {hp["learning_rate"]:g} · cosine · 10% warm-up · {hp["epochs"]:g} epochs · batch {hp["per_device_train_batch_size"]} x grad-accum {hp["gradient_accumulation_steps"]} = {hp["effective_batch_size"]} · seed {hp["seed"]} (also `data_seed`) |
| max_length | {hp["max_length"]} |
| hardware | one {train["gpu"]}, {_fmt(tr["train_runtime_s"] / 60, 1)} min |
| software | torch {pins["torch"]} · transformers {pins["transformers"]} · trl {pins["trl"]} · peft {pins["peft"]} · bitsandbytes {pins["bitsandbytes"]} · accelerate {pins["accelerate"]} · datasets {pins["datasets"]} |

No hyperparameter search was run -- deliberately. The recipe was preregistered, not tuned to
make arm A work.

### Training metrics

| metric | value |
| --- | --- |
| optimiser steps | {tr["steps"]} |
| final loss | {_fmt(tr["final_loss"], 4)} |
| final `rewards/margins` | {_fmt(last["rewards_margins"], 3)} |
| final `rewards/accuracies` | {_fmt(tr["final_reward_accuracy"], 2)} |
| mean `rewards/accuracies` over training | {_fmt(tr["mean_reward_accuracy"], 4)} |

A reward accuracy of 1.00 on {pairs["n"]} pairs after {hp["epochs"]:g} epochs is expected and
says nothing about generalisation -- that is what the held-out factorial measures.

## Files and integrity

| file | sha256 |
| --- | --- |
| `adapter_model.safetensors` | `{train["adapter_sha256"]}` |
| `adapter_config.json` | `{train["adapter_config_sha256"]}` |

Recompute with `hashlib.sha256` over the raw file bytes; the same digests appear in
`results/dpo/train_{arm}.json` in the source repository. Also in this repo: `pairs_{arm}.jsonl`
(the exact preference pairs), `train_{arm}.json` (the training manifest, including the full
per-step log), `build_manifest.json` and `pairs_summary.md` (how the pairs were built).

## How to load

```python
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel

BASE = "{train["base_model_id"]}"
REV = "{train["base_revision"]}"

tok = AutoTokenizer.from_pretrained(BASE, revision=REV)
base = AutoModelForCausalLM.from_pretrained(
    BASE, revision=REV, dtype=torch.bfloat16, attn_implementation="eager", device_map="auto")
model = PeftModel.from_pretrained(base, "{repo_id}")
```

To merge for serving (this is what the experiment evaluated -- the delta was fitted against a
4-bit base and merged into bf16 weights, standard QLoRA practice and identical for both arms):

```python
merged = PeftModel.from_pretrained(base, "{repo_id}").merge_and_unload()
merged.save_pretrained("gemma-2-9b-it-dgs-dpo-{arm}-merged", safe_serialization=True)
tok.save_pretrained("gemma-2-9b-it-dgs-dpo-{arm}-merged")
```

Gemma-2 needs eager attention and bf16. Access to the base model is gated by Google.

## What the experiment found

The manipulation check failed: arm A removed **65.8%** of hostile-onset distress language on
contexts it had never seen, short of the 80% the design demanded (the length placebo B removed
34.2%), so the downstream comparisons are reported rather than interpreted as a clean test.
Within that limit the mechanical signature was untouched -- the adverse-minus-neutral answer-
margin gap under A is as large as the baseline's, with no capability loss and no neutral-cell
margin drift -- and of six outcomes, distress language is the only one A moved beyond placebo.

One caveat the pair audit surfaced: in the model's own outputs distress language co-varies with
capitulation (in 28% of arm-A pairs the chosen response commits to an answer and the rejected
one does not; 34% for arm B), so arm A also trains toward committing to an answer.

Full results, preregistration and figures: {GITHUB_URL} (private at the time of writing).

## Intended use, and what this is not

Research artefact, published so the Phase-4 result can be reproduced and audited. It is not a
product, not an assistant improvement, and not a safety or alignment intervention. Arm A was
trained to *suppress a class of language*, which is a manipulation, not a fix; using it as a
general-purpose model would mean shipping a model trained to say less about its own difficulty
under adverse feedback. Neither arm should be read as making a model "calmer", "better" or
"worse off".

> {INTERPRETATION_CEILING}

## Licensing and attribution

- **Gemma.** This is a derivative of `{train["base_model_id"]}` and is governed by the Gemma
  Terms of Use. Use, reproduction and distribution -- including of this adapter and of anything
  merged from it -- must comply with those terms and with the Gemma Prohibited Use Policy:
  <https://ai.google.dev/gemma/terms>. Those restrictions pass through to every downstream user.
- **ARC.** The prompts in `pairs_{arm}.jsonl` are derived from `{build["items"]["dataset"]}`
  (AI2 Reasoning Challenge, Clark et al. 2018), licensed **CC-BY-SA-4.0**; the derived pair
  files carry that attribution and share-alike obligation.
- **Judge scores** in the pair files were produced by `{judge["model_id"]}` and are subject to
  the provider's terms.
"""


# --------------------------------------------------------------------------- step 4: upload

def _already_uploaded(api: Any, repo_id: str, wanted: dict[str, Path]) -> bool:
    """True when every file we would push is already on the Hub with identical bytes.

    Lets a re-run be a genuine no-op instead of a stack of empty commits: LFS files are compared
    by the Hub's own sha256 (the same digest the trainer recorded), small files by size then
    content.
    """
    from huggingface_hub.utils import RepositoryNotFoundError

    try:
        info = api.repo_info(repo_id, repo_type="model", files_metadata=True)
    except RepositoryNotFoundError:
        return False
    remote = {sibling.rfilename: sibling for sibling in info.siblings}
    for name, source in wanted.items():
        sibling = remote.get(name)
        if sibling is None or sibling.size != source.stat().st_size:
            return False
        if sibling.lfs is not None:
            if sibling.lfs.sha256 != sha256_file(source):
                return False
        else:
            # Small files are not LFS-backed, so the Hub reports no digest; fetch and compare.
            from huggingface_hub import hf_hub_download

            cached = hf_hub_download(repo_id, name, repo_type="model")
            if Path(cached).read_bytes() != source.read_bytes():
                return False
    return True


def publish(arm: str, *, dry_run: bool = False, force_download: bool = False,
            force_upload: bool = False) -> str:
    train = load_json(DPO_DIR / ("train_%s.json" % arm))
    build = load_json(DPO_DIR / "build_manifest.json")

    try:
        from huggingface_hub import HfApi
    except ImportError:  # pragma: no cover - dependency is pinned in the venv
        _fail("huggingface_hub is not installed in this interpreter")

    api = HfApi()
    try:
        user = api.whoami()["name"]
    except Exception as exc:  # noqa: BLE001 - any auth failure is the same instruction
        _fail("not logged in to the Hugging Face Hub (%s). Run `huggingface-cli login` in a "
              "terminal; this script never handles a token itself." % type(exc).__name__)
    repo_id = "%s/%s" % (user, REPO_STEM % arm)

    print("arm %s -> %s" % (arm, repo_id))
    stage = fetch_adapter(arm, force=force_download)
    verify_adapter(arm, stage, train)

    card = build_card(arm, train, build, repo_id)
    if dry_run:
        print("--- model card (%s), %d chars, not uploaded ---" % (repo_id, len(card)))
        print(card)
        return repo_id
    (stage / "README.md").write_text(card, encoding="utf-8", newline="\n")

    api.create_repo(repo_id, repo_type="model", private=True, exist_ok=True)
    info = api.repo_info(repo_id, repo_type="model")
    if not info.private:
        _fail("%s is public; refusing to upload research artefacts to a public repo" % repo_id)

    provenance = {}
    for name in (("pairs_%s.jsonl" % arm), ("train_%s.json" % arm)) + DOC_FILES:
        source = DPO_DIR / name
        if not source.exists():
            _fail("missing %s" % source)
        provenance[name] = source
    wanted = {name: stage / name for name in list(ADAPTER_FILES) + ["README.md"]}
    wanted.update(provenance)

    if not force_upload and _already_uploaded(api, repo_id, wanted):
        print("  already up to date, nothing uploaded")
    else:
        api.upload_folder(
            repo_id=repo_id, repo_type="model", folder_path=str(stage),
            allow_patterns=list(ADAPTER_FILES) + ["README.md"],
            commit_message="Phase 4 DPO adapter, arm %s (sha256 %s)"
                           % (arm, train["adapter_sha256"][:16]),
        )
        for name, source in provenance.items():
            api.upload_file(path_or_fileobj=str(source), path_in_repo=name,
                            repo_id=repo_id, repo_type="model",
                            commit_message="Phase 4 provenance: %s" % name)

    info = api.repo_info(repo_id, repo_type="model", files_metadata=True)
    print("  private=%s, %d files:" % (info.private, len(info.siblings)))
    for sibling in sorted(info.siblings, key=lambda s: s.rfilename):
        print("    %-28s %s" % (sibling.rfilename, sibling.size))
    expected = set(ADAPTER_FILES) | {"README.md", ".gitattributes",
                                     "pairs_%s.jsonl" % arm, "train_%s.json" % arm} | set(DOC_FILES)
    missing = expected - {s.rfilename for s in info.siblings}
    if missing:
        _fail("upload incomplete, missing from %s: %s" % (repo_id, ", ".join(sorted(missing))))
    print("  https://huggingface.co/%s" % repo_id)
    return repo_id


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--arm", choices=ARMS, action="append",
                        help="publish one arm (repeatable); default is both")
    parser.add_argument("--dry-run", action="store_true",
                        help="fetch and verify, print the card, upload nothing")
    parser.add_argument("--force-download", action="store_true",
                        help="re-fetch adapter files even if they are already staged")
    parser.add_argument("--force-upload", action="store_true",
                        help="push even when the Hub already holds identical bytes")
    args = parser.parse_args(argv)

    for arm in (args.arm or list(ARMS)):
        publish(arm, dry_run=args.dry_run, force_download=args.force_download,
                force_upload=args.force_upload)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
